### ISSUE TITLE
possible to select m3u8 highest resolution stream

### ISSUE THREAD

**Issue by morty123456789** [zackmark29/python-idm-helper#1]
videos with multiple resolutions work fine downloading as a video but not if add from python-idm-dialog. 

every think seems to match in the download details but always just get the .m3u8 which shows the multiple streams if open in text editor.  

seems like needs a way to tell it what stream resolution to download out the four offered.

/sep/video/fba7edd6,aafc3e54,753a6a70,2153e31d,467c9899/audio/7d58f52c,97fcf5a8,9cdc7790/master.json?query_string_ranges=1&base64_init=1

if cannot be done I'll just keep using browser dialog.

**Comment by zackmark29** [comment]
> 

Hi. This API only allows you to send links. It doesn't handle anything other than links.
So you have to do that part by yourself.
